#################################################
# BetterExp by Athena_PvP                       #
# https://github.com/Athena-PvP/BetterExp       #
#################################################

Grass: 0.3
Dirt: 0.1
Wood: 0.5
Sand: 0.2
